const mongoose=require('mongoose');
const {Schema}=mongoose;

const problemSchema=new Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
      type:String,
      required:true,
    },
    difficulty:{
        type:String,
        enum:["Easy","Medium","Hard"],
        required:true,
    },
    tags:{
        type:String,
        enum:["Array", "LinkedList", "Tree", "Graph", "Dp", "String", "Math", "Sorting", "Stack"],
        required:true,
    },
    role:{
        type:String,
        enum:['admin','user'],
        default:'user',
    },
    visibleTestCases:[{
        input:{
            type:String,
            required:true,
        },
        output:{
            type:String,
            required:true,
        },
        explaination:{
            type:String,
            required:true,
        }
    }],
     invisibleTestCases:[{
        input:{
            type:String,
            required:true,
        },
        output:{
            type:String,
            required:true,
        }
    }],
     startcode:[{
        language:{
            type:String,
            required:true,
        },
        initialCode:{
            type:String,
            required:true,
        }
    }],
    refrencesolution:[{
        language:{
            type:String,
            required:true,
        },
        solution:{
            type:String,
            required:true,
        }
    }],
    problemCreator:{
        type:Schema.Types.ObjectId,
        ref:'user',
        required:true
    }
},
{timestamps:true})

const Problem=mongoose.model("problems",problemSchema);
module.exports=Problem;